apiVersion: v1
kind: Service
metadata:
    name: "aksshir-27fc"
    labels:
        app: "aksshir-27fc"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aksshir-27fc"