on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: crshir.azurecr.io
        username: ${{ secrets.acr_crshir_username }}
        password: ${{ secrets.acr_crshir_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t crshir.azurecr.io/aksshir:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push crshir.azurecr.io/aksshir:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksshir_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks-shiraeba | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks-shiraeba`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks-shiraeba
        container-registry-url: crshir.azurecr.io
        container-registry-username: ${{ secrets.acr_crshir_username }}
        container-registry-password: ${{ secrets.acr_crshir_password }}
        secret-name: aksshirdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks-shiraeba
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          crshir.azurecr.io/aksshir:${{ github.sha }}
        imagepullsecrets: |
          aksshirdockerauth
